"""Execute the validation framework notebook and export a scorecard artifact.

Phase 2.5.3 requires an end-to-end run against the live v3 database plus a
committed scorecard artifact. This script standardizes that run so the same
commands can be reused when the database is available.
"""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path

DEFAULT_DATABASE_PATH = Path("data/nhl_data.db")
DEFAULT_NOTEBOOK_PATH = Path("notebooks/model_validation_framework.ipynb")
DEFAULT_OUTPUT_DIR = Path("artifacts")
EXECUTED_NOTEBOOK_NAME = "model_validation_framework.executed.ipynb"
SCORECARD_OUTPUT_NAME = "validation_scorecard_latest.md"
SCORECARD_SENTINEL = "VALIDATION SCORECARD"


def _run_command(cmd: list[str]) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, check=True, capture_output=True, text=True)


def _extract_scorecard_text(executed_notebook_path: Path) -> str:
    with executed_notebook_path.open("r", encoding="utf-8") as f:
        notebook = json.load(f)

    for cell in notebook.get("cells", []):
        if cell.get("cell_type") != "code":
            continue
        for output in cell.get("outputs", []):
            if output.get("output_type") != "stream":
                continue
            text_value = output.get("text", "")
            if isinstance(text_value, list):
                text_value = "".join(text_value)
            if SCORECARD_SENTINEL in text_value:
                return text_value.strip()

    raise ValueError(
        "Could not find a code-cell stream output containing "
        f"{SCORECARD_SENTINEL!r}."
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--db-path", type=Path, default=DEFAULT_DATABASE_PATH)
    parser.add_argument("--notebook-path", type=Path, default=DEFAULT_NOTEBOOK_PATH)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    args = parser.parse_args()

    if not args.db_path.exists():
        raise FileNotFoundError(
            f"Database not found at {args.db_path}. "
            "Phase 2.5.3 requires the live populated nhl_data.db file."
        )

    if not args.notebook_path.exists():
        raise FileNotFoundError(f"Notebook not found at {args.notebook_path}.")

    args.output_dir.mkdir(parents=True, exist_ok=True)
    executed_notebook_path = args.output_dir / EXECUTED_NOTEBOOK_NAME
    scorecard_output_path = args.output_dir / SCORECARD_OUTPUT_NAME

    _run_command(
        [
            "python",
            "-m",
            "jupyter",
            "nbconvert",
            "--to",
            "notebook",
            "--execute",
            str(args.notebook_path),
            "--output",
            EXECUTED_NOTEBOOK_NAME,
            "--output-dir",
            str(args.output_dir),
        ]
    )

    scorecard_text = _extract_scorecard_text(executed_notebook_path)
    scorecard_output_path.write_text(
        "# Validation Scorecard (Latest Run)\n\n"
        "Generated by `scripts/export_validation_scorecard.py` from the executed "
        "validation notebook.\n\n"
        "```text\n"
        f"{scorecard_text}\n"
        "```\n",
        encoding="utf-8",
    )

    print(f"Executed notebook written to: {executed_notebook_path}")
    print(f"Scorecard artifact written to: {scorecard_output_path}")


if __name__ == "__main__":
    main()
